### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by andybak** [hadiDanial/SVGImporter#2]
Hiya,

I'm looking around for an SVG library for https://github.com/icosa-gallery/open-brush/ and I found this and your Spline library.

Neither have a licence specified that I can see so I can't even look at them currently.

What licence did you have in mind?

**Comment by hadiDanial** [comment]
Hey!

I hadn't considered a license to be honest, since I didn't think anyone would be interested in this.

The projects are fairly limited in SVG feature support at the moment. 

What is your use case, if you don't mind me asking? And does this library do the job in its current state or would you need additional features?

I'll take a look at licenses and let you know.

Also - that project looks incredible!

**Comment by andybak** [comment]
Hi there. I ended up forking https://github.com/needle-mirror/com.unity.vectorgraphics to add runtime import support. 

> Also - that project looks incredible!

Thanks!

**Comment by andybak** [comment]
Ooops. Didn't mean to close this - that's your job!
